<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LLamaSharp" Version="0.27.0" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
        <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.29.0" />
        <PackageReference Include="OllamaSharp" Version="5.4.30" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\RAGGit.Core\RAGGit.Core.csproj" />
    </ItemGroup>
</Project>
